name: Prymal Shipbob Inventory Extraction
run-name: ${{ github.actor }} - Shipbob Inventory Extraction 
on: 
  push:
    paths:
      - '**/extraction/shipbob_inventory**'
  schedule:
    - cron: '0 6 * * *'  # Runs at 6 AM every day
jobs:
  shipbob_inventory_etl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner. The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Set up Python env
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r extraction/requirements.txt
    
      - name: Extract Shipbob Inventory
        env: 
          SHIPBOB_API_SECRET: ${{ secrets.SHIPBOB_API_SECRET }}
          AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
          S3_PRYMAL: ${{ secrets.S3_PRYMAL }}
        run: python extraction/shipbob_inventory/shipbob_inventory.py 

      # - name: Run Shopify Glue Crawlers
      #   env: 
      #     AWS_ACCESS_KEY:  ${{ secrets.AWS_ACCESS_KEY }}
      #     AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_SECRET }}
      #   run: python prymal/data_pipelines/shopify/order_data/shopify_crawlers.py 
        

      - run: echo "Job status - ${{ job.status }}."
